KAFKA_CLUSTR = ['XXXXXX:9092']

SERIALIZATIO_JSON = 'json'

KFK_PRODUCER = 'Producer'
KFK_CONSUMER = 'Consumer'

INGESTION_TOPIC = 'gndr-ingst'
GNDR_SERV_TOPIC = 'gndr-rslt'

CONSUMER_GRP_MODEL1 = 'CG-MODEL1'
CONSUMER_GRP_MODEL2 = 'CG-MODEL2'
CONSUMER_GRP_MODEL3 = 'CG-MODEL3'

MNG_HOST = ""
MNG_PORT = 27000
MNG_USER_NAME = ""
MNG_DBNAME = ""
MNG_PASSWORD = ""
MNG_SSL = False
MNG_SOURCE = None

MODEL1_COLNM = 'Model1'
MODEL2_COLNM = 'Model2'
MODEL3_COLNM = 'Model3'

OUTPUT_COLNM = 'gender'

GNDR_MALE = 'male'
GNDR_FEMALE = 'female'

MODE1_NM = 'MODEL1'
MODE2_NM = 'MODEL2'
MODE3_NM = 'MODEL3'
